<a href="https://colab.research.google.com/github/RANA1804/Introduction_to_machine_learning/blob/main/02_Working__with_CSV_Files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


##CSV File Manipulation in Python
The utilization of Python's Pandas library for handling CSV (Comma-Separated Values) files is a frequent practice in data analysis and manipulation. Pandas, being a robust data manipulation library, offers structures like DataFrame, specifically designed for efficient manipulation of tabular data, commonly encountered in CSV files.

## Import Required Libraries

In [ ]:
# Connect with Google drive
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd

## Open a Local CSV File

In [ ]:
csv_path = r"/content/drive/MyDrive/1.ML/datasets/Iris.csv"
df = pd.read_csv(csv_path)
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

## **Open a CSV File from an URL**


*  ### requests Module:
The requests module in the Python standard library is a popular HTTP library used for making HTTP requests to interact with web resources. It simplifies the process of sending HTTP requests and handling their responses. The module provides a user-friendly API for common HTTP methods such as GET, POST, PUT, DELETE, and more.
  With the requests module, you can include parameters, headers, cookies, and handle various authentication methods when making HTTP requests. Additionally, it automatically manages connection pooling and supports features like session handling and persistent connections.



*   ### io Module:
The io module in the Python library provides a versatile infrastructure for handling input/output operations. It offers classes and functions to work with streams, files, and other file-like objects. This module enables a unified approach to managing diverse data sources, facilitating seamless manipulation of input and output operations in Python programs.

In [ ]:
import requests
from io import StringIO

In [ ]:
uri = "https://raw.githubusercontent.com/codeforamerica/ohana-api/master/data/sample-csv/addresses.csv"
req = requests.get(uri)
data = StringIO(req.text)
data

In [ ]:
df = pd.read_csv(data)
df

ðŸ”‘ Note: A response with a status code of 200 indicates a successful HTTP request. The HTTP status code 200 OK is one of the standard HTTP response codes, and it means that the request was successful, the server processed the request, and the requested information is contained in the response body.

## sep Parameter
The sep parameter specifies the delimiter or separator used in the CSV file to distinguish between different fields or columns. By default, the comma (,) is used as the separator. However, in some cases, CSV files might use other delimiters such as tabs (\t) or semicolons (;).

In [ ]:
# Read a Tab Separated Values File (TSV) with pandas
tsv_path = "/content/drive/MyDrive/1.ML/datasets/movie_titles_metadata.tsv"
df = pd.read_csv(tsv_path, sep="\t")
df.head() # By defult it will show 5 rows

In [ ]:
# Giving the name of the collumns
collumn_name = ["Sl.name", "Movie_name", "Release_year", "rating", "Votes", "Movies_type"]
df = pd.read_csv(tsv_path, sep="\t", names = collumn_name)
df

## Index_Col parameter

In Python, the index_col parameter is used in functions like pandas.read_csv() to specify which column from the input data should be used as the index for the DataFrame. It allows you to set a specific column as the index, providing a labeled structure for the data in the DataFrame.

In [ ]:
pd.read_csv(csv_path, index_col = "Id").head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

## header Parameter
The header parameter specifies which row should be considered as the header (column names) when reading the CSV file. By default, the first row is treated as the header. If you set header=None, pandas will not use any row as the header, and columns will be labeled with numeric indices. You can also provide an integer row number to use as the header, or a list of integers to skip multiple initial rows.

In [ ]:
test_csv_path = "/content/drive/MyDrive/1.ML/datasets/test.csv"
pd.read_csv(test_csv_path)

In [ ]:
# Change the Header row
pd.read_csv(test_csv_path, header=1)

## Usecols parameter

In Python, specifically in the context of tools like pandas for data manipulation, the usecols parameter is used to selectively read and load only specific columns from a dataset when importing data from a file, such as a CSV or Excel file. By specifying usecols, you can choose a subset of columns to be loaded into a DataFrame, saving memory and improving performance when working with large datasets.

In [ ]:
train_csv_path = "/content/drive/MyDrive/1.ML/datasets/aug_train.csv"
pd.read_csv(train_csv_path, usecols = ["enrollee_id", "city",	"city_development_index",	"gender"]).head()

   enrollee_id      city  city_development_index gender
0         8949  city_103                   0.920   Male
1        29725   city_40                   0.776   Male
2        11561   city_21                   0.624    NaN
3        33241  city_115                   0.789    NaN
4          666  city_162                   0.767   Male

## skiprows / nrows Parameter


*   skiprows Parameter: The skiprows parameter allows you to specify the number of rows at the beginning of the CSV file to skip while reading. You can pass an integer representing the number of rows to skip or a list of row indices (0-based) that should be skipped.

*   nrows Parameter: The nrows parameter is used to limit the number of rows read from the CSV file. You can pass an integer representing the maximum number of rows to read.

In [ ]:
pd.read_csv(train_csv_path)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [ ]:
pd.read_csv(train_csv_path, skiprows=[2,4]).head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0

In [ ]:
# Select only first 100 rows
pd.read_csv(train_csv_path,nrows=100)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12081,city_65,0.802,Male,Has relevent experience,Full time course,Graduate,STEM,9,50-99,Pvt Ltd,1,33,0.0
96,7364,city_160,0.920,NaN,No relevent experience,Full time course,High School,NaN,2,100-500,Pvt Ltd,1,142,0.0
97,11184,city_74,0.579,NaN,No relevent experience,Full time course,Graduate,STEM,2,100-500,Pvt Ltd,1,34,0.0
98,7016,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,2,14,1.0
99,8695,city_11,0.550,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,10/49,Pvt Ltd,2,27,1.0

## encoding Parameter

In Python, the encoding parameter refers to the character encoding scheme used to interpret and represent text data when reading from or writing to files. It specifies the mapping between binary data and text characters, ensuring proper interpretation of the content. Common encodings include 'utf-8', 'ascii', and 'latin-1'.

When reading a CSV file, it's important to use the correct encoding to ensure that the data is interpreted correctly. If you encounter issues where characters are not displayed correctly or you see encoding-related errors, specifying the appropriate encoding can help resolve these problems.

In [ ]:
zomato_csv_data = "/content/drive/MyDrive/1.ML/datasets/zomato.csv"
#pd.read_csv(zomato_csv_data) # It will throw a error so we have to encode it
pd.read_csv(zomato_csv_data,encoding= "latin-1").head()

## dtype Parameter
In Python, particularly within libraries like NumPy or pandas, the dtype parameter refers to the data type parameter. It is used to specify or infer the data type of elements within arrays, data structures, or variables. This parameter ensures that the data is interpreted and processed correctly, providing control over how numeric values are stored and manipulated.

In [ ]:
df = pd.read_csv(train_csv_path)
df.head()

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [ ]:
df = pd.read_csv(train_csv_path, dtype = {"target" : "int8"}).head()
df

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             5 non-null      int64
 1   city                    5 non-null      object
 2   city_development_index  5 non-null      float64
 3   gender                  3 non-null      object
 4   relevent_experience     5 non-null      object
 5   enrolled_university     4 non-null      object
 6   education_level         5 non-null      object
 7   major_discipline        5 non-null      object
 8   experience              5 non-null      object
 9   company_size            2 non-null      object
 10  company_type            3 non-null      object
 11  last_new_job            5 non-null      object
 12  training_hours          5 non-null      int64
 13  target                  5 non-null      int8
dtypes: float64(1), int64(2), int8(1), object(10)
memory usage: 653.0+ bytes

## Handling Dates

Handling dates in Python involves managing and manipulating date and time information using the datetime module. This module provides classes and functions to represent and work with dates, times, and intervals. Operations include parsing and formatting date strings, performing arithmetic with dates, and handling time zones.

In [ ]:
ipl_csv_path = "/content/drive/MyDrive/1.ML/datasets/IPL Matches 2008-2020.csv"
df2 = pd.read_csv(ipl_csv_path)
df2

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [ ]:
df = pd.read_csv(ipl_csv_path, parse_dates = ["date"])
df

In [ ]:
df.info()

##converters Parameter
The converters parameter in the pandas read_csv() function is used to provide a dictionary of functions that allow you to customize the way specific columns are converted or transformed during the reading process. It's a powerful tool when you need more control over how the data is processed as it's being read from the CSV file.

In [ ]:
df = pd.read_csv(ipl_csv_path)
df

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [ ]:
def renameTeam(name):
  if name == "Kolkata Knight Riders":
    return "KKR"
  else:
     return (name)

In [ ]:
# Apply converter
df = pd.read_csv(ipl_csv_path, converters = {"team1" : renameTeam, "team2": renameTeam})
df.head()

## na_values Parameters

In Python, specifically in the context of tools like pandas used for data analysis, the na_values parameter is often associated with functions that read data from external sources, such as pandas.read_csv(). This parameter allows you to specify a list of values that should be treated as missing or NaN (Not a Number) when reading data from a file, making it easier to handle and process datasets with missing or undefined values.

In [ ]:
pd.read_csv(train_csv_path).info()

In [ ]:
# Select "Null values" as "Nal" for example
pd.read_csv(train_csv_path, na_values= "Male").head()

## Chunksize parameter (Load a Huge Dataset in Chunks)
In Python, the chunksize parameter is often used in the context of processing data in chunks or segments. For example, when working with large datasets, the chunksize parameter is commonly employed in libraries like pandas when reading or processing data in smaller, more manageable portions. This parameter allows users to specify the number of rows to be read or processed at a time, helping to optimize memory usage and overall performance.

In [ ]:
dfs = pd.read_csv (train_csv_path, chunksize = 5000)
for chunk in dfs:
  print(chunk.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)